### ISSUE TITLE
Not work on Radiolink AT9

### ISSUE THREAD

**Issue by gppsoft** [gatis-ozols/ppm_stick#1]
Not work on Radiolink AT9. I try to upload .bin file from debug folder via  ST-Link Utility.

**Comment by gatis-ozols** [comment]
Hi, could You please elaborate more?
Is the gamepad device detected in Windows?
Is the board connected to Your AT9 correctly?
Is the AT9 configured correctly? (it could be that You have to configure it as student transmitter or something, I really do not know how it is in AT9)
